import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateTables1742478618976 implements MigrationInterface {
    name = 'CreateTables1742478618976'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "question_history" DROP CONSTRAINT "question_history_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "question_history" DROP CONSTRAINT "question_history_category_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "question_history" DROP CONSTRAINT "question_history_skill_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "categories" DROP CONSTRAINT "categories_parent_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "skills" DROP CONSTRAINT "skills_category_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "user_skill_levels" DROP CONSTRAINT "user_skill_levels_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "user_skill_levels" DROP CONSTRAINT "user_skill_levels_skill_id_fkey"`);
        await queryRunner.query(`DROP INDEX "public"."idx_question_history_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_question_history_hash"`);
        await queryRunner.query(`DROP INDEX "public"."idx_question_history_asked_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_question_history_skill_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_question_history_user_hash"`);
        await queryRunner.query(`DROP INDEX "public"."idx_categories_parent_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_categories_path"`);
        await queryRunner.query(`DROP INDEX "public"."idx_categories_name"`);
        await queryRunner.query(`DROP INDEX "public"."idx_categories_search"`);
        await queryRunner.query(`DROP INDEX "public"."idx_skills_category_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_skills_name"`);
        await queryRunner.query(`DROP INDEX "public"."idx_user_skill_levels_skill_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_user_skill_levels_level"`);
        await queryRunner.query(`DROP INDEX "public"."idx_user_skill_levels_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_email"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_username"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_settings"`);
        await queryRunner.query(`ALTER TABLE "skills" DROP CONSTRAINT "skills_skill_name_category_id_key"`);
        await queryRunner.query(`ALTER TABLE "user_skill_levels" DROP CONSTRAINT "user_skill_levels_user_id_skill_id_key"`);
        await queryRunner.query(`ALTER TABLE "question_history" DROP COLUMN "asked_at"`);
        await queryRunner.query(`ALTER TABLE "question_history" ADD "asked_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "categories" ALTER COLUMN "level" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "categories" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "categories" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "categories" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "categories" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "skills" ALTER COLUMN "difficulty_base" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "skills" ALTER COLUMN "difficulty_base" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "skills" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "skills" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "skills" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "skills" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user_skill_levels" ALTER COLUMN "skill_level" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_skill_levels" ALTER COLUMN "skill_level" SET DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "user_skill_levels" ALTER COLUMN "confidence" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_skill_levels" ALTER COLUMN "confidence" SET DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE "user_skill_levels" ALTER COLUMN "total_attempts" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_skill_levels" ALTER COLUMN "correct_attempts" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_skill_levels" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "user_skill_levels" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user_skill_levels" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "user_skill_levels" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "is_active" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "settings" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "skills" ADD CONSTRAINT "UQ_1676e90569c202416957bee654f" UNIQUE ("skill_name", "category_id")`);
        await queryRunner.query(`ALTER TABLE "user_skill_levels" ADD CONSTRAINT "UQ_4407d190543c361827a3c382eec" UNIQUE ("user_id", "skill_id")`);
        await queryRunner.query(`ALTER TABLE "question_history" ADD CONSTRAINT "FK_367dcbb830f30ad5fee90194dae" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "question_history" ADD CONSTRAINT "FK_4b3aee644d237441a5ebe1b25eb" FOREIGN KEY ("category_id") REFERENCES "categories"("category_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "question_history" ADD CONSTRAINT "FK_3eb68a1cb572718a169a165e4a7" FOREIGN KEY ("skill_id") REFERENCES "skills"("skill_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "categories" ADD CONSTRAINT "FK_88cea2dc9c31951d06437879b40" FOREIGN KEY ("parent_id") REFERENCES "categories"("category_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "skills" ADD CONSTRAINT "FK_47dd0ade7ed449a7aca9b9e6752" FOREIGN KEY ("category_id") REFERENCES "categories"("category_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_skill_levels" ADD CONSTRAINT "FK_802968b3c93ba8db95d1671c6fb" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_skill_levels" ADD CONSTRAINT "FK_446a0cc27d14e4035ce71684ed4" FOREIGN KEY ("skill_id") REFERENCES "skills"("skill_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user_skill_levels" DROP CONSTRAINT "FK_446a0cc27d14e4035ce71684ed4"`);
        await queryRunner.query(`ALTER TABLE "user_skill_levels" DROP CONSTRAINT "FK_802968b3c93ba8db95d1671c6fb"`);
        await queryRunner.query(`ALTER TABLE "skills" DROP CONSTRAINT "FK_47dd0ade7ed449a7aca9b9e6752"`);
        await queryRunner.query(`ALTER TABLE "categories" DROP CONSTRAINT "FK_88cea2dc9c31951d06437879b40"`);
        await queryRunner.query(`ALTER TABLE "question_history" DROP CONSTRAINT "FK_3eb68a1cb572718a169a165e4a7"`);
        await queryRunner.query(`ALTER TABLE "question_history" DROP CONSTRAINT "FK_4b3aee644d237441a5ebe1b25eb"`);
        await queryRunner.query(`ALTER TABLE "question_history" DROP CONSTRAINT "FK_367dcbb830f30ad5fee90194dae"`);
        await queryRunner.query(`ALTER TABLE "user_skill_levels" DROP CONSTRAINT "UQ_4407d190543c361827a3c382eec"`);
        await queryRunner.query(`ALTER TABLE "skills" DROP CONSTRAINT "UQ_1676e90569c202416957bee654f"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "settings" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "is_active" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "user_skill_levels" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "user_skill_levels" ADD "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "user_skill_levels" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "user_skill_levels" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "user_skill_levels" ALTER COLUMN "correct_attempts" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_skill_levels" ALTER COLUMN "total_attempts" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_skill_levels" ALTER COLUMN "confidence" SET DEFAULT 1.0`);
        await queryRunner.query(`ALTER TABLE "user_skill_levels" ALTER COLUMN "confidence" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_skill_levels" ALTER COLUMN "skill_level" SET DEFAULT 0.0`);
        await queryRunner.query(`ALTER TABLE "user_skill_levels" ALTER COLUMN "skill_level" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "skills" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "skills" ADD "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "skills" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "skills" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "skills" ALTER COLUMN "difficulty_base" SET DEFAULT 0.0`);
        await queryRunner.query(`ALTER TABLE "skills" ALTER COLUMN "difficulty_base" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "categories" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "categories" ADD "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "categories" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "categories" ADD "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "categories" ALTER COLUMN "level" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "question_history" DROP COLUMN "asked_at"`);
        await queryRunner.query(`ALTER TABLE "question_history" ADD "asked_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "user_skill_levels" ADD CONSTRAINT "user_skill_levels_user_id_skill_id_key" UNIQUE ("user_id", "skill_id")`);
        await queryRunner.query(`ALTER TABLE "skills" ADD CONSTRAINT "skills_skill_name_category_id_key" UNIQUE ("skill_name", "category_id")`);
        await queryRunner.query(`CREATE INDEX "idx_users_settings" ON "users" ("settings") `);
        await queryRunner.query(`CREATE INDEX "idx_users_username" ON "users" ("username") `);
        await queryRunner.query(`CREATE INDEX "idx_users_email" ON "users" ("email") `);
        await queryRunner.query(`CREATE INDEX "idx_user_skill_levels_user_id" ON "user_skill_levels" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_user_skill_levels_level" ON "user_skill_levels" ("skill_level") `);
        await queryRunner.query(`CREATE INDEX "idx_user_skill_levels_skill_id" ON "user_skill_levels" ("skill_id") `);
        await queryRunner.query(`CREATE INDEX "idx_skills_name" ON "skills" ("skill_name") `);
        await queryRunner.query(`CREATE INDEX "idx_skills_category_id" ON "skills" ("category_id") `);
        await queryRunner.query(`CREATE INDEX "idx_categories_search" ON "categories" ("search_vector") `);
        await queryRunner.query(`CREATE INDEX "idx_categories_name" ON "categories" ("category_name") `);
        await queryRunner.query(`CREATE INDEX "idx_categories_path" ON "categories" USING GiST ("path") `);
        await queryRunner.query(`CREATE INDEX "idx_categories_parent_id" ON "categories" ("parent_id") `);
        await queryRunner.query(`CREATE INDEX "idx_question_history_user_hash" ON "question_history" ("user_id", "question_hash") `);
        await queryRunner.query(`CREATE INDEX "idx_question_history_skill_id" ON "question_history" ("skill_id") `);
        await queryRunner.query(`CREATE INDEX "idx_question_history_asked_at" ON "question_history" ("asked_at") `);
        await queryRunner.query(`CREATE INDEX "idx_question_history_hash" ON "question_history" ("question_hash") `);
        await queryRunner.query(`CREATE INDEX "idx_question_history_user_id" ON "question_history" ("user_id") `);
        await queryRunner.query(`ALTER TABLE "user_skill_levels" ADD CONSTRAINT "user_skill_levels_skill_id_fkey" FOREIGN KEY ("skill_id") REFERENCES "skills"("skill_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_skill_levels" ADD CONSTRAINT "user_skill_levels_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "skills" ADD CONSTRAINT "skills_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "categories"("category_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "categories" ADD CONSTRAINT "categories_parent_id_fkey" FOREIGN KEY ("parent_id") REFERENCES "categories"("category_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "question_history" ADD CONSTRAINT "question_history_skill_id_fkey" FOREIGN KEY ("skill_id") REFERENCES "skills"("skill_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "question_history" ADD CONSTRAINT "question_history_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "categories"("category_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "question_history" ADD CONSTRAINT "question_history_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("user_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
